name: "🧹 Chore / Maintenance"
description: Non-feature work for expert_system (refactors, CI, deps).
labels: [chore]
title: "chore: <short summary>"
body:
  - type: input
    id: goal
    attributes:
      label: Goal
      placeholder: e.g., Speed up backward chaining memoization
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks / acceptance
      description: Bullet list with the concrete steps.
      placeholder: |
        - [ ] replace recursion with iterative stack
        - [ ] update unit tests covering loops
        - [ ] document behavior in README
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area touched
      options:
        - Parser
        - Inference engine
        - CLI / UX
        - Tooling / CI
        - Docs
