---
name: "Documentation update"
description: "Keep README and notes accurate"
title: "[DOCS] <short summary>"
labels:
  - docs
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Clarify backward chaining example
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: File / section
      description: Point to the paragraph, anchor, or file path to edit.
      placeholder: README.md > Usage > Inference example
  - type: textarea
    id: change
    attributes:
      label: What should change?
      description: Short description or bullet list of the edits.
      placeholder: Replace screenshot + add CLI command snippet.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Links, references, or follow-up tasks.
