name: "✨ Expert System idea"
description: Suggest enhancements to inference, CLI UX, or tooling.
labels: [enhancement]
title: "feat: <short summary>"
body:
  - type: markdown
    attributes:
      value: >
        Describe the scenario, why it matters for expert_system at 42, and which
        part (parser, inference, CLI, tooling, docs) you want to extend.
  - type: input
    id: scenario
    attributes:
      label: Summary
      placeholder: Add parser flag to trace tokenization
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem or need
      description: What pain point, subject requirement, or KB limitation drives this?
      placeholder: We cannot inspect how parentheses change precedence.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Outline the idea at a high level (files, data flow, UX).
      placeholder: >
        Add --trace-parser to print tokens, AST nodes, and link to inference logs.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Main area
      description: Pick the primary part affected.
      multiple: true
      options:
        - Parser / lexer
        - Inference engine
        - CLI / UX
        - Tooling / tests
        - Documentation
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Acceptance criteria, sample KB, links, or dependencies.
