name: "✨ Expert System idea"
description: Suggest enhancements to inference, CLI UX, or tooling.
labels: [enhancement]
title: "feat: <short summary>"
body:
  - type: markdown
    attributes:
      value: |
        Describe the scenario the expert_system should support and how it helps
        42 students building knowledge bases faster.
  - type: input
    id: scenario
    attributes:
      label: Scenario / pain point
      placeholder: Need a way to see which rules fired for a query
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe CLI flags, data structures, or UI copy you'd like.
      render: markdown
  - type: checkboxes
    id: checklist
    attributes:
      label: Ready to help?
      options:
        - label: I can work on this change
        - label: It won't break existing knowledge base files
